# Generated by Django 5.0.2 on 2024-02-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('airplane_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_class_seat', models.IntegerField(default=6)),
                ('business_class_seat', models.IntegerField(default=12)),
                ('economy_class_seat', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_code', models.CharField(max_length=100)),
                ('airport_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.CharField(max_length=100)),
                ('arrival_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='griffin_flight.airplanes')),
                ('arrival_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrivals', to='griffin_flight.airports')),
                ('departure_loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departures', to='griffin_flight.airports')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('classSeat', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('pay_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='griffin_flight.flights')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='griffin_flight.users')),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.SmallIntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='griffin_flight.books')),
            ],
        ),
    ]
