# Generated by Django 5.0.2 on 2024-02-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('griffin_flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'managed': False},
        ),
    ]
