# Generated by Django 5.0.2 on 2024-02-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('griffin_flight', '0002_alter_admins_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admins',
            table='admins',
        ),
    ]
