# Generated by Django 5.0.2 on 2024-02-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('griffin_flight', '0003_alter_admins_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplanes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='airports',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='passports',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
