# Generated by Django 5.0.2 on 2024-02-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('griffin_flight', '0004_alter_airplanes_options_alter_airports_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airplanes',
            table='airplanes',
        ),
        migrations.AlterModelTable(
            name='airports',
            table='airports',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
        migrations.AlterModelTable(
            name='flights',
            table='flights',
        ),
        migrations.AlterModelTable(
            name='passports',
            table='passports',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
